//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QLCP6_2.Module.BusinessObjects.QuanLyQuanCaPhe6
{

    public partial class Ban : XPLiteObject
    {
        string fMaBan;
        [Key]
        [Size(5)]
        public string MaBan
        {
            get { return fMaBan; }
            set { SetPropertyValue<string>(nameof(MaBan), ref fMaBan, value); }
        }
        KhachHang fMaKhachHang;
        [Size(5)]
        [Association(@"BanReferencesKhachHang")]
        public KhachHang MaKhachHang
        {
            get { return fMaKhachHang; }
            set { SetPropertyValue<KhachHang>(nameof(MaKhachHang), ref fMaKhachHang, value); }
        }
        int fSoBan;
        public int SoBan
        {
            get { return fSoBan; }
            set { SetPropertyValue<int>(nameof(SoBan), ref fSoBan, value); }
        }
        string fViTri;
        [Size(30)]
        public string ViTri
        {
            get { return fViTri; }
            set { SetPropertyValue<string>(nameof(ViTri), ref fViTri, value); }
        }
        string fTrangThai;
        [Size(30)]
        public string TrangThai
        {
            get { return fTrangThai; }
            set { SetPropertyValue<string>(nameof(TrangThai), ref fTrangThai, value); }
        }
    }

}
