//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QLCP6_2.Module.BusinessObjects.QuanLyQuanCaPhe6
{

    public partial class HoaDon : XPLiteObject
    {
        string fMaHoaDon;
        [Key]
        [Size(5)]
        public string MaHoaDon
        {
            get { return fMaHoaDon; }
            set { SetPropertyValue<string>(nameof(MaHoaDon), ref fMaHoaDon, value); }
        }
        KhachHang fMaKhachHang;
        [Size(5)]
        [Association(@"HoaDonReferencesKhachHang")]
        public KhachHang MaKhachHang
        {
            get { return fMaKhachHang; }
            set { SetPropertyValue<KhachHang>(nameof(MaKhachHang), ref fMaKhachHang, value); }
        }
        NhanVien fMaNhanVien;
        [Size(5)]
        [Association(@"HoaDonReferencesNhanVien")]
        public NhanVien MaNhanVien
        {
            get { return fMaNhanVien; }
            set { SetPropertyValue<NhanVien>(nameof(MaNhanVien), ref fMaNhanVien, value); }
        }
        DateTime fNgayDatHang;
        public DateTime NgayDatHang
        {
            get { return fNgayDatHang; }
            set { SetPropertyValue<DateTime>(nameof(NgayDatHang), ref fNgayDatHang, value); }
        }
        
        string fTrangThai;
        [Size(30)]
        public string TrangThai
        {
            get { return fTrangThai; }
            set { SetPropertyValue<string>(nameof(TrangThai), ref fTrangThai, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Tổng tiền")]
        public double TongTien
        {
            get
            {
                double tien = 0;
                foreach(ChiTietHoaDon item in ChiTietHoaDons)
                {
                    tien = item.ThanhTien;
                }
                return tien;
            }
        }
        [Association(@"ChiTietHoaDonReferencesHoaDon")]
        public XPCollection<ChiTietHoaDon> ChiTietHoaDons { get { return GetCollection<ChiTietHoaDon>(nameof(ChiTietHoaDons)); } }
        [Association(@"ThanhToanReferencesHoaDon")]
        public XPCollection<ThanhToan> ThanhToans { get { return GetCollection<ThanhToan>(nameof(ThanhToans)); } }
        [Association(@"VanChuyenNgoaiReferencesHoaDon")]
        public XPCollection<VanChuyenNgoai> VanChuyenNgoais { get { return GetCollection<VanChuyenNgoai>(nameof(VanChuyenNgoais)); } }
        [Association(@"VanChuyenNoiBoReferencesHoaDon")]
        public XPCollection<VanChuyenNoiBo> VanChuyenNoiBoes { get { return GetCollection<VanChuyenNoiBo>(nameof(VanChuyenNoiBoes)); } }
    }

}
