//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QLCP6_2.Module.BusinessObjects.QuanLyQuanCaPhe6
{

    public partial class LoaiHang : XPLiteObject
    {
        string fMaLoaiHang;
        [Key]
        [Size(5)]
        public string MaLoaiHang
        {
            get { return fMaLoaiHang; }
            set { SetPropertyValue<string>(nameof(MaLoaiHang), ref fMaLoaiHang, value); }
        }
        string fTenLoaiHang;
        [Size(30)]
        public string TenLoaiHang
        {
            get { return fTenLoaiHang; }
            set { SetPropertyValue<string>(nameof(TenLoaiHang), ref fTenLoaiHang, value); }
        }
        [Association(@"SanPhamReferencesLoaiHang")]
        public XPCollection<SanPham> SanPhams { get { return GetCollection<SanPham>(nameof(SanPhams)); } }
    }

}
