//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QLCP6_2.Module.BusinessObjects.QuanLyQuanCaPhe6
{

    public partial class NhanVien : XPLiteObject
    {
        string fMaNhanVien;
        [Key]
        [Size(5)]
        public string MaNhanVien
        {
            get { return fMaNhanVien; }
            set { SetPropertyValue<string>(nameof(MaNhanVien), ref fMaNhanVien, value); }
        }
        TaiKhoan fMaTaiKhoan;
        [Indexed(Name = @"UQ__NhanVien__AD7C652836AB8B2F", Unique = true)]
        [Size(5)]
        [Association(@"NhanVienReferencesTaiKhoan")]
        public TaiKhoan MaTaiKhoan
        {
            get { return fMaTaiKhoan; }
            set { SetPropertyValue<TaiKhoan>(nameof(MaTaiKhoan), ref fMaTaiKhoan, value); }
        }
        string fHoTen;
        [Size(30)]
        public string HoTen
        {
            get { return fHoTen; }
            set { SetPropertyValue<string>(nameof(HoTen), ref fHoTen, value); }
        }
        string fGioiTinh;
        [Size(3)]
        public string GioiTinh
        {
            get { return fGioiTinh; }
            set { SetPropertyValue<string>(nameof(GioiTinh), ref fGioiTinh, value); }
        }
        string fEmail;
        [Size(30)]
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
        }
        string fDiaChi;
        [Size(30)]
        public string DiaChi
        {
            get { return fDiaChi; }
            set { SetPropertyValue<string>(nameof(DiaChi), ref fDiaChi, value); }
        }
        string fSoDienThoai;
        [Size(15)]
        public string SoDienThoai
        {
            get { return fSoDienThoai; }
            set { SetPropertyValue<string>(nameof(SoDienThoai), ref fSoDienThoai, value); }
        }
        string fCMND;
        [Size(20)]
        public string CMND
        {
            get { return fCMND; }
            set { SetPropertyValue<string>(nameof(CMND), ref fCMND, value); }
        }
        string fCaLamViec;
        [Size(10)]
        public string CaLamViec
        {
            get { return fCaLamViec; }
            set { SetPropertyValue<string>(nameof(CaLamViec), ref fCaLamViec, value); }
        }
        string fViTri;
        [Size(30)]
        public string ViTri
        {
            get { return fViTri; }
            set { SetPropertyValue<string>(nameof(ViTri), ref fViTri, value); }
        }
        string fChucVu;
        [Size(30)]
        public string ChucVu
        {
            get { return fChucVu; }
            set { SetPropertyValue<string>(nameof(ChucVu), ref fChucVu, value); }
        }
        DateTime fNgayVaoLam;
        public DateTime NgayVaoLam
        {
            get { return fNgayVaoLam; }
            set { SetPropertyValue<DateTime>(nameof(NgayVaoLam), ref fNgayVaoLam, value); }
        }
        double fLuong;
        public double Luong
        {
            get { return fLuong; }
            set { SetPropertyValue<double>(nameof(Luong), ref fLuong, value); }
        }
        double fThuong;
        public double Thuong
        {
            get { return fThuong; }
            set { SetPropertyValue<double>(nameof(Thuong), ref fThuong, value); }
        }
        [Association(@"HoaDonReferencesNhanVien")]
        public XPCollection<HoaDon> HoaDons { get { return GetCollection<HoaDon>(nameof(HoaDons)); } }
        [Association(@"NhapReferencesNhanVien")]
        public XPCollection<Nhap> Nhaps { get { return GetCollection<Nhap>(nameof(Nhaps)); } }
        [Association(@"VanChuyenNoiBoReferencesNhanVien")]
        public XPCollection<VanChuyenNoiBo> VanChuyenNoiBoes { get { return GetCollection<VanChuyenNoiBo>(nameof(VanChuyenNoiBoes)); } }
        [Association(@"XuatReferencesNhanVien")]
        public XPCollection<Xuat> Xuats { get { return GetCollection<Xuat>(nameof(Xuats)); } }
    }

}
