//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QLCP6_2.Module.BusinessObjects.QuanLyQuanCaPhe6
{

    public partial class QuanLy : XPLiteObject
    {
        string fMaQuanLy;
        [Key]
        [Size(5)]
        public string MaQuanLy
        {
            get { return fMaQuanLy; }
            set { SetPropertyValue<string>(nameof(MaQuanLy), ref fMaQuanLy, value); }
        }
        TaiKhoan fMaTaiKhoan;
        [Indexed(Name = @"UQ__QuanLy__AD7C6528B619734D", Unique = true)]
        [Size(5)]
        [Association(@"QuanLyReferencesTaiKhoan")]
        public TaiKhoan MaTaiKhoan
        {
            get { return fMaTaiKhoan; }
            set { SetPropertyValue<TaiKhoan>(nameof(MaTaiKhoan), ref fMaTaiKhoan, value); }
        }
        string fHoTen;
        [Size(30)]
        public string HoTen
        {
            get { return fHoTen; }
            set { SetPropertyValue<string>(nameof(HoTen), ref fHoTen, value); }
        }
        string fGioiTinh;
        [Size(3)]
        public string GioiTinh
        {
            get { return fGioiTinh; }
            set { SetPropertyValue<string>(nameof(GioiTinh), ref fGioiTinh, value); }
        }
        string fDiaChi;
        [Size(30)]
        public string DiaChi
        {
            get { return fDiaChi; }
            set { SetPropertyValue<string>(nameof(DiaChi), ref fDiaChi, value); }
        }
        string fCMND;
        [Size(20)]
        public string CMND
        {
            get { return fCMND; }
            set { SetPropertyValue<string>(nameof(CMND), ref fCMND, value); }
        }
        string fEmail;
        [Size(30)]
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
        }
        string fSoDienThoai;
        [Size(15)]
        public string SoDienThoai
        {
            get { return fSoDienThoai; }
            set { SetPropertyValue<string>(nameof(SoDienThoai), ref fSoDienThoai, value); }
        }
    }

}
