//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QLCP6_2.Module.BusinessObjects.QuanLyQuanCaPhe6
{

    public partial class VanChuyenNgoai : XPLiteObject
    {
        string fMaVanChuyen;
        [Key]
        [Size(5)]
        public string MaVanChuyen
        {
            get { return fMaVanChuyen; }
            set { SetPropertyValue<string>(nameof(MaVanChuyen), ref fMaVanChuyen, value); }
        }
        HoaDon fMaHoaDon;
        [Size(5)]
        [Association(@"VanChuyenNgoaiReferencesHoaDon")]
        public HoaDon MaHoaDon
        {
            get { return fMaHoaDon; }
            set { SetPropertyValue<HoaDon>(nameof(MaHoaDon), ref fMaHoaDon, value); }
        }
        string fTenShipper;
        [Size(30)]
        public string TenShipper
        {
            get { return fTenShipper; }
            set { SetPropertyValue<string>(nameof(TenShipper), ref fTenShipper, value); }
        }
        string fSoDienThoaiShipper;
        [Size(15)]
        public string SoDienThoaiShipper
        {
            get { return fSoDienThoaiShipper; }
            set { SetPropertyValue<string>(nameof(SoDienThoaiShipper), ref fSoDienThoaiShipper, value); }
        }
        DateTime fNgayGiaoHang;
        public DateTime NgayGiaoHang
        {
            get { return fNgayGiaoHang; }
            set { SetPropertyValue<DateTime>(nameof(NgayGiaoHang), ref fNgayGiaoHang, value); }
        }
        string fTrangThai;
        [Size(30)]
        public string TrangThai
        {
            get { return fTrangThai; }
            set { SetPropertyValue<string>(nameof(TrangThai), ref fTrangThai, value); }
        }
    }

}
